I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/day_1/d1s4.rpy", line 165, in script
    jump d1s5
ScriptError: could not find label 'd1s5'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/day_1/d1s4.rpy", line 165, in script
    jump d1s5
  File "C:\Users\blue_\OneDrive\Documentos\renpy-8.1.3-sdk\renpy\ast.py", line 1992, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\blue_\OneDrive\Documentos\renpy-8.1.3-sdk\renpy\script.py", line 1013, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'd1s5'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.1.3.23091805
Rounded GUI 1.1.0
Thu Feb  8 13:14:04 2024
